name: tree-stats
channels:
  - defaults
  - conda-forge
  - kaspermunch
dependencies:
  - jupyterlab
  - nodejs
  - scipy
  - pytables
  - git
  - seaborn
  - scikit-learn
  - tqdm
  - multiprocess
  - tskit
  - msprime
  - libcblas
  - gsl
  - geneinfo
